# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
